import { api } from "../client";

export const adminMediaApi = {
  uploadManual: (...args: Parameters<typeof api.uploadMediaVideo>) => api.uploadMediaVideo(...args),
  uploadAutomatic: (...args: Parameters<typeof api.uploadAutomaticMediaVideo>) => api.uploadAutomaticMediaVideo(...args),
  uploadReplacement: (...args: Parameters<typeof api.uploadReplacementMediaVideo>) => api.uploadReplacementMediaVideo(...args),
  listAssets: (...args: Parameters<typeof api.listMediaAssets>) => api.listMediaAssets(...args),
  preflightUpload: (...args: Parameters<typeof api.preflightMediaUpload>) => api.preflightMediaUpload(...args),
  categories: (...args: Parameters<typeof api.managedCategories>) => api.managedCategories(...args),
  moveAsset: (...args: Parameters<typeof api.moveManagedContent>) => api.moveManagedContent(...args),
  deleteFailedAsset: (...args: Parameters<typeof api.deleteFailedMediaAsset>) => api.deleteFailedMediaAsset(...args),
  bulkDeleteFailedAssets: (...args: Parameters<typeof api.bulkDeleteFailedMediaAssets>) => api.bulkDeleteFailedMediaAssets(...args),
  archiveAsset: (...args: Parameters<typeof api.archiveMediaAsset>) => api.archiveMediaAsset(...args),
  returnToReview: (...args: Parameters<typeof api.returnTranscriptToReview>) => api.returnTranscriptToReview(...args),
  profiles: (...args: Parameters<typeof api.listTranscriptionProfiles>) => api.listTranscriptionProfiles(...args),
  schemes: (...args: Parameters<typeof api.listTranscriptionSchemes>) => api.listTranscriptionSchemes(...args),
  jobs: (...args: Parameters<typeof api.listTranscriptionJobs>) => api.listTranscriptionJobs(...args),
  startTranscription: (...args: Parameters<typeof api.startMediaTranscription>) => api.startMediaTranscription(...args),
  getJob: (...args: Parameters<typeof api.getTranscriptionJob>) => api.getTranscriptionJob(...args),
  cancelJob: (...args: Parameters<typeof api.cancelTranscriptionJob>) => api.cancelTranscriptionJob(...args),
  retryJob: (...args: Parameters<typeof api.retryTranscription>) => api.retryTranscription(...args),
  bulkRetryJobs: (...args: Parameters<typeof api.bulkRetryTranscriptions>) => api.bulkRetryTranscriptions(...args),
  versions: (...args: Parameters<typeof api.listTranscriptVersions>) => api.listTranscriptVersions(...args),
  previewVersion: (...args: Parameters<typeof api.previewTranscriptVersion>) => api.previewTranscriptVersion(...args),
  previewVersionTimeline: (...args: Parameters<typeof api.previewTranscriptVersionTimeline>) => api.previewTranscriptVersionTimeline(...args),
  createRevision: (...args: Parameters<typeof api.createTranscriptRevision>) => api.createTranscriptRevision(...args),
  reviewVersion: (...args: Parameters<typeof api.reviewTranscriptVersion>) => api.reviewTranscriptVersion(...args),
  publishVersion: (...args: Parameters<typeof api.publishTranscriptVersion>) => api.publishTranscriptVersion(...args),
  publicationJob: (...args: Parameters<typeof api.getTranscriptPublicationJob>) => api.getTranscriptPublicationJob(...args),
  externalRoots: (...args: Parameters<typeof api.listExternalMediaRoots>) => api.listExternalMediaRoots(...args),
  externalSources: (...args: Parameters<typeof api.listExternalMediaSources>) => api.listExternalMediaSources(...args),
  createExternalSource: (...args: Parameters<typeof api.createExternalMediaSource>) => api.createExternalMediaSource(...args),
  updateExternalSource: (...args: Parameters<typeof api.updateExternalMediaSource>) => api.updateExternalMediaSource(...args),
  scanExternalSource: (...args: Parameters<typeof api.scanExternalMediaSource>) => api.scanExternalMediaSource(...args),
  externalEntries: (...args: Parameters<typeof api.listExternalMediaEntries>) => api.listExternalMediaEntries(...args),
  enqueueExternal: (...args: Parameters<typeof api.enqueueExternalMedia>) => api.enqueueExternalMedia(...args),
  previewEnqueueExternal: (...args: Parameters<typeof api.previewEnqueueExternalMedia>) => api.previewEnqueueExternalMedia(...args),
};
